tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bash"
brew "calc"
brew "node"
brew "p7zip"
brew "python"
brew "tmux"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "cyberduck"
cask "docker"
cask "font-fira-code"
cask "gpg-suite"
cask "protonmail-bridge"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
